In [2]:
import numpy as np

#### Mathematial Operations

In [3]:
a1 = np.array([1,8,6,7,9])
a1

array([1, 8, 6, 7, 9])

In [5]:
a2 = np.array([2, 8, 7, 6, 3])
a2

array([2, 8, 7, 6, 3])

In [6]:
a1 + a2

array([ 3, 16, 13, 13, 12])

In [7]:
a1 - a2

array([-1,  0, -1,  1,  6])

In [8]:
a1 * a2

array([ 2, 64, 42, 42, 27])

In [9]:
a1 / a2

array([0.5       , 1.        , 0.85714286, 1.16666667, 3.        ])

In [10]:
ans = a1 ** 2
ans

array([ 1, 64, 36, 49, 81])

In [11]:
np.sqrt(ans)

array([1., 8., 6., 7., 9.])

In [12]:
a3 = np.array([1.2, 2.5, 3.7, 4.9])
a3

array([1.2, 2.5, 3.7, 4.9])

In [13]:
np.floor(a3)

array([1., 2., 3., 4.])

In [14]:
np.ceil(a3)

array([2., 3., 4., 5.])

In [15]:
np.round(a3)

array([1., 2., 4., 5.])

#### Combining Arrays

In [ ]:
a1

In [ ]:
a2

In [16]:
np.concatenate((a1, a2))

array([1, 8, 6, 7, 9, 2, 8, 7, 6, 3])

In [17]:
arr1 = np.array([[3, 5, 7], [1, 2, 9], [4, 6, 8]])
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [18]:
print(arr1)

[[3 5 7]
 [1 2 9]
 [4 6 8]]


In [19]:
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
np.vstack((arr1, arr2))

array([[3, 5, 7],
       [1, 2, 9],
       [4, 6, 8],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
np.hstack((arr1, arr2))

array([[3, 5, 7, 1, 2, 3],
       [1, 2, 9, 4, 5, 6],
       [4, 6, 8, 7, 8, 9]])

In [22]:
arr1.flatten()

array([3, 5, 7, 1, 2, 9, 4, 6, 8])

#### Splitting Arrays

In [23]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr

array([1, 2, 3, 4, 5, 6])

In [24]:
np.split(arr, 3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [25]:
arr2 = np.array([[1, 2, 3, 4, 5, 6], 
                [7, 8, 9, 10, 11, 12]])
arr2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [26]:
np.hsplit(arr2, 3)

[array([[1, 2],
        [7, 8]]),
 array([[ 3,  4],
        [ 9, 10]]),
 array([[ 5,  6],
        [11, 12]])]

In [27]:
np.vsplit(arr2, 2)

[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]])]

#### Searching in Array

In [28]:
a1

array([1, 8, 6, 7, 9])

In [29]:
np.where(a1 == 7)

(array([3]),)

In [30]:
a3 = np.array([1, 3, 5, 6, 3, 7, 1])
a3

array([1, 3, 5, 6, 3, 7, 1])

In [31]:
np.where(a3 == 3)

(array([1, 4]),)

In [32]:
np.where(a3 > 3)

(array([2, 3, 5]),)

In [33]:
arr1

array([[3, 5, 7],
       [1, 2, 9],
       [4, 6, 8]])

In [34]:
np.where(arr1 == 5)

(array([0]), array([1]))

In [35]:
arr3 = np.array([[1, 2, 3], [2, 5, 7], [4, 5, 2]])
arr3

array([[1, 2, 3],
       [2, 5, 7],
       [4, 5, 2]])

In [36]:
np.where(arr3 == 2)

(array([0, 1, 2]), array([1, 0, 2]))

#### Sorting of Array

In [38]:
a1

array([1, 8, 6, 7, 9])

In [37]:
np.sort(a1)

array([1, 6, 7, 8, 9])

In [ ]:
# Find how to sort in descending order

In [39]:
arr3

array([[1, 2, 3],
       [2, 5, 7],
       [4, 5, 2]])

In [40]:
np.sort(arr3)

array([[1, 2, 3],
       [2, 5, 7],
       [2, 4, 5]])

In [ ]:
# Find how to sort in descending order
# Find how to sort col-wise & row-wise

#### Aggregating & Statistical Functions

In [ ]:
a1

In [41]:
np.sum(a1)

np.int64(31)

In [42]:
np.mean(a1)

np.float64(6.2)

In [43]:
np.median(a1)

np.float64(7.0)

In [44]:
np.max(a1)

np.int64(9)

In [45]:
np.min(a1)

np.int64(1)

In [46]:
np.std(a1)

np.float64(2.7856776554368237)

In [47]:
np.var(a1)

np.float64(7.76)

In [48]:
arr4 = np.array([[1, 2, 3], [4, 5, 6]])
arr4

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
np.sum(arr4)

np.int64(21)

In [50]:
np.sum(arr4, axis=1)    # Row-wise sum

array([ 6, 15])

In [51]:
np.sum(arr4, axis=0)    # Col-wise sum

array([5, 7, 9])