### Boolean Indexing (Filtering Array)

In [1]:
import numpy as np

In [4]:
arr = np.array([10, 15, 20, 25, 30])

In [ ]:
arr

In [ ]:
l = [True, False, True, True, False]
l

In [ ]:
arr[l]
# arr[[True, False, True, True, False]]

In [ ]:
arr

In [ ]:
l2 = (arr%2 == 0)
l2

In [ ]:
arr[l2]

In [ ]:
arr[arr%2 == 0]

In [ ]:
age = np.array([42, 18, 22, 13, 16])

In [ ]:
age

In [ ]:
age[age > 18]

In [ ]:
age[age == 22]

In [ ]:
a2 = np.array([[3, 5, 7], [1, 2, 9], [6, 4, 2]])
a2

In [ ]:
l1 = [True, False, True]

In [ ]:
a2[l1]

### Boolean Mask (Masking Array)

In [3]:
arr

NameError: name 'arr' is not defined

In [ ]:
l

In [ ]:
print(np.ma.array(arr, mask=l))    # arr[l]

In [ ]:
odd_numbers = np.ma.array(arr, mask=arr%2==0)   # arr[arr%2==0]
print(odd_numbers)

### Reshaping Array

In [ ]:
a2

In [ ]:
a2.flatten()    # Converts Multi-dimensional array into 1D array

In [ ]:
a2.reshape(-1)    # Converts Multi-dimensional array into 1D array

In [ ]:
a2.ravel()    # Converts Multi-dimensional array into 1D array

In [ ]:
a1d = np.arange(12)
a1d

In [ ]:
a1d.reshape(4, 3)   # Converts 1D array into Multi-dimensoinal array e.g., 1D to 2D array

In [ ]:
a1d.reshape(2, -1)   # -1 means automatically decides the possible dimension

In [ ]:
a1d.reshape(-1, 6)   # -1 means automatically decides the possible dimension

In [ ]:
a1d.reshape(-1, 3)   # -1 means automatically decides the possible dimension

In [ ]:
a1d.reshape(2, 3, 2)   # Converts 1D array into Multi-dimensoinal array e.g., 1D to 3D array

### Broadcasting of Array

###### Broadcasting is a powerful mechanism in NumPy that allows array operations between arrays of different shapes without copying data.

###### In simple terms: Broadcasting allows you to automatically expand smaller arrays to match the shape of larger arrays during operations like addition, multiplication, etc.

---

###### **🧠 Why is Broadcasting Needed?**
###### When doing arithmetic on arrays, NumPy performs the operation element-wise. But what if the shapes don’t match?

###### Instead of throwing an error, broadcasting stretches the smaller array to fit the shape of the larger one — virtually (no memory copy!).

###### **📏 Types of Broadcasting**

###### 1. Scalar Broadcasting
###### 2. Vector Broadcasting
###### 3. Matrix Broadcasting

---

##### 🔸 1. Scalar Broadcasting

###### A scalar is a single number. When you operate a scalar with an array, the scalar is broadcast to the shape of the array.

In [5]:
arr

array([10, 15, 20, 25, 30])

In [6]:
# Scaler => One elemnet array
s1 = [3]
s2 = 5
s3 = np.array([6])

In [7]:
arr + s2

array([15, 20, 25, 30, 35])

In [8]:
arr + s1

array([13, 18, 23, 28, 33])

In [9]:
arr + 8

array([18, 23, 28, 33, 38])

In [10]:
arr + s3

array([16, 21, 26, 31, 36])

---

##### 🔸 2. Vector Broadcasting

###### (a) Row Vector Broadcasting (1D)
###### (b) Column Vector Broadcasting

---

###### **(a) Row Vector Broadcasting (1D)**
###### A 1D array can be broadcast across each row of a 2D array if shapes are compatible.

In [11]:
a1 = np.array([[1, 2, 3],
              [4, 5, 6]])   # shape (2, 3)

a2 = np.array([10, 20, 30])  # shape (3,)

print(a1 + a2)

# a1.shape = (2, 3)
# a2.shape = (3,) → broadcast to (2, 3) ➡️ Added to each row

[[11 22 33]
 [14 25 36]]


###### **(b) Column Vector Broadcasting**
###### Use reshape() to turn a 1D array into a column vector (n x 1) and broadcast it column-wise.

In [12]:
a1 = np.array([[1, 2, 3],
              [4, 5, 6]])

# a2 = np.array([[10], [20]])
a2 = np.array([10, 20]).reshape(-1, 1)

print(a1 + a2)

# a2.shape = (2, 1) → added down each row

[[11 12 13]
 [24 25 26]]


---

##### 🔸 3. Matrix Broadcasting

###### Broadcasting happens between matrices of different shapes if they satisfy broadcasting rules.

###### **✅ Rules:**
###### Compare shapes from right to left

###### Dimensions are compatible if:
- ###### Same, or
- ###### One is 1

In [15]:
a1 = np.array([[1], [2]])
a2 = np.array([[10, 20, 30]])

print(a1)
# print()
print(a2)
# print()

a3 = a1 + a2
print(a3)

# a1 → (2, 1) → expanded across columns
# a2 → (1, 3) → expanded across rows
# Result shape → (2, 3)

[[1]
 [2]]
[[10 20 30]]
[[11 21 31]
 [12 22 32]]


In [16]:
# ❌ Incompatible Shapes Example:

a1 = np.array([[1, 2], [3, 4]])
a2 = np.array([1, 2, 3])

print(a1)
print()
print(a2)

print(a1 + a2)

# ValueError: operands could not be broadcast together with shapes (2,2) (3,)
# Shapes (2,2) and (3,) cannot match by any rule.

[[1 2]
 [3 4]]

[1 2 3]


ValueError: operands could not be broadcast together with shapes (2,2) (3,) 

In [20]:
# ❌ Incompatible Shapes Example:

a1 = np.array([[2, 5, 4, 1], [6, 5, 8, 9], [3, 2, 5, 4]])
a2 = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [3, 2, 1, 4], [7, 8, 5, 6]])

print(a1)
print()
print(a2)
# print()

a3 = a1 + a2

print(a3)

[[2 5 4 1]
 [6 5 8 9]
 [3 2 5 4]]

[[1 2 3 4]
 [4 5 6 7]
 [3 2 1 4]
 [7 8 5 6]]


ValueError: operands could not be broadcast together with shapes (3,4) (4,4) 