In [ ]:
import numpy as np

In [ ]:
dir(np)

## Creating an Array

In [4]:
l = [1, 4, 6, 8]

l

[1, 4, 6, 8]

In [5]:
arr = np.array(l)
print(arr)

[1 4 6 8]


In [6]:
a2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [8]:
a3 = np.ones(5)
a3

array([1., 1., 1., 1., 1.])

In [9]:
a4 = np.eye(3)
a4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
ar1 = np.zeros((3, 3))
ar1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
ar2 = np.ones((3, 3))
ar2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
ar3 = np.arange(10)
ar3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
ar4 = np.arange(1, 11)
ar4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
ar5 = np.arange(1, 11, 2)
ar5

array([1, 3, 5, 7, 9])

In [15]:
ar6 = np.linspace(1, 10, 5)
ar6

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [16]:
arr7 = np.full(5, 2)
arr7

array([2, 2, 2, 2, 2])

In [17]:
arr8 = np.full((3, 3), 9)
arr8

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [18]:
r1 = np.random.rand(3, 3)
r1

array([[0.7590127 , 0.54159527, 0.20301553],
       [0.16211836, 0.36306142, 0.84902753],
       [0.37263921, 0.02586298, 0.93833714]])

In [19]:
r2 = np.random.rand(5)
r2

array([0.54340013, 0.52098649, 0.58408894, 0.09104825, 0.2733211 ])

In [20]:
r3 = np.random.randint(5)
r3

4

In [30]:
r4 = np.random.randint(3, 10)
r4

6

In [31]:
r5 = np.random.randint(3, 10, 5)
r5

array([7, 6, 6, 4, 3], dtype=int32)

In [32]:
r6 = np.random.randint(3, 10, (3, 3))
r6

array([[5, 5, 4],
       [4, 6, 4],
       [3, 5, 4]], dtype=int32)

## Indexing of Array

In [33]:
a = np.arange(1, 10)

In [34]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
print(a[0])

1


In [36]:
print(a[3])

4


In [37]:
print(a[-1])

9


In [38]:
print(a[-3])

7


In [39]:
a2 = np.random.randint(1, 10, (3, 3))
a2

array([[1, 9, 9],
       [3, 6, 8],
       [2, 1, 2]], dtype=int32)

In [40]:
print(a2[0][1])

9


In [41]:
print(a2[2][0])

2


In [42]:
print(a2[0, 1])

9


In [43]:
print(a2[1, 2])

8


In [44]:
print(a2)

[[1 9 9]
 [3 6 8]
 [2 1 2]]


In [45]:
print(a2[0, 1])

9


## Slicing on Array

In [46]:
a = np.arange(3, 10)
a

array([3, 4, 5, 6, 7, 8, 9])

In [47]:
a[0:3]

array([3, 4, 5])

In [48]:
a[-1:-5:-1]

array([9, 8, 7, 6])

In [49]:
a[2:6]

array([5, 6, 7, 8])

In [50]:
a

array([3, 4, 5, 6, 7, 8, 9])

In [51]:
a[0:]

array([3, 4, 5, 6, 7, 8, 9])

In [52]:
a[0::1]

array([3, 4, 5, 6, 7, 8, 9])

In [53]:
a[0::2]

array([3, 5, 7, 9])

In [54]:
a[::]

array([3, 4, 5, 6, 7, 8, 9])

In [55]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3])

In [56]:
a2 = np.random.randint(1, 10, (3, 3))
print(a2)

[[7 8 1]
 [4 1 2]
 [6 8 1]]


In [57]:
a2[0:2, 2]

array([1, 2], dtype=int32)

In [58]:
a2[0:, 1]

array([8, 1, 8], dtype=int32)

In [59]:
a2[1, 0:2]

array([4, 1], dtype=int32)

In [60]:
a2

array([[7, 8, 1],
       [4, 1, 2],
       [6, 8, 1]], dtype=int32)

In [61]:
a2[:, :]

array([[7, 8, 1],
       [4, 1, 2],
       [6, 8, 1]], dtype=int32)

In [62]:
a2[0:, 1:]

array([[8, 1],
       [1, 2],
       [8, 1]], dtype=int32)

## Shape, Size, and Datatype of Array

In [63]:
a

array([3, 4, 5, 6, 7, 8, 9])

In [64]:
print(a.shape)

(7,)


In [65]:
a2

array([[7, 8, 1],
       [4, 1, 2],
       [6, 8, 1]], dtype=int32)

In [66]:
print(a2.shape)

(3, 3)


In [67]:
print(a.size)

7


In [68]:
print(a2.size)

9


In [69]:
print(a.dtype)

int64


In [70]:
print(a2.dtype)

int32


In [72]:
print(a.ndim)
print(a2.ndim)

1
2


## Mathematical Operations on Array

In [ ]:
a1 = np.arange(11, 20)
a2 = np.arange(5, 14)

In [ ]:
a1

In [ ]:
a2

In [ ]:
a1 + a2

In [ ]:
a1 * a2

In [ ]:
a3 = np.array([16, 81, 25, 121, 9])

np.sqrt(a3)